databases:
  - name: movie_theater_db
    plan: free
    databaseName: movie_theater_db
    user: movie_theater_user

services:
  - type: web
    plan: free
    name: movie_theater_booking
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn movie_theater_booking.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movie_theater_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

