# Generated by Django 4.2.11 on 2025-10-05 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_movie_description_movie_release_date_seat_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='user_name',
        ),
    ]
