# Generated by Django 4.2.11 on 2025-10-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_user_booking_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
